// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using UnityEngine;

    public struct _a06d71d53be2a314a98d5dcd8c25b91e_5c322f881b5045e8bcfdc2b9337e3417 : IEntityCommand
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
        }

        public static unsafe _a06d71d53be2a314a98d5dcd8c25b91e_5c322f881b5045e8bcfdc2b9337e3417 FromInterop(System.IntPtr data, System.Int32 dataSize) 
        {
            if (dataSize != 0) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 0) " +
                    "for command with ID 8");
            }

            var orig = new _a06d71d53be2a314a98d5dcd8c25b91e_5c322f881b5045e8bcfdc2b9337e3417();
            var comp = (Interop*)data;
            return orig;
        }

        
        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint Sender { get; set; }
        public uint GetComponentType() => 8;
        
        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }
        
        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }
        
        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() {
            return default;
        }

        public void NullEntityRefs(Entity entity) {
        }
        
        
        public static void Serialize(_a06d71d53be2a314a98d5dcd8c25b91e_5c322f881b5045e8bcfdc2b9337e3417 commandData, IOutProtocolBitStream bitStream)
        {
        }
        
        public static _a06d71d53be2a314a98d5dcd8c25b91e_5c322f881b5045e8bcfdc2b9337e3417 Deserialize(IInProtocolBitStream bitStream, Entity entity, MessageTarget target)
        {
    
            return new _a06d71d53be2a314a98d5dcd8c25b91e_5c322f881b5045e8bcfdc2b9337e3417()
            {
                Entity = entity,
                Routing = target,
            };   
        }
    }

}
